### ISSUE TITLE
the linux instalation instructions link is broken

### ISSUE THREAD

**Issue by almeidacavalcante** [FeitianSmartcardReader/R301#3]
Hi, 

I'd be very glad to be able to test this scripts on my machine, but the linux instalation instruction link is broken: http://pcsclite.alioth.debian.org/ccid/shouldwork.html

could you help me on that?

thank you, sir.

**Comment by FeitianSmartcardReader** [comment]
@almeidacavalcante  
Thanks for your feedback, the reader is CCID standard and that link change to beblow
https://ccid.apdu.fr/ccid/shouldwork.html

the driver source code can find from CCID repo: https://github.com/LudovicRousseau/CCID

**Comment by almeidacavalcante** [comment]
> @almeidacavalcante
> Thanks for your feedback, the reader is CCID standard and that link change to beblow
> https://ccid.apdu.fr/ccid/shouldwork.html
> 
> the driver source code can find from CCID repo: https://github.com/LudovicRousseau/CCID

Hi, thank you for this very quick answer !! I'll check it out...
