### ISSUE TITLE
Feitian iR301 Smart Card Reader Does not Get Powered On When Connected to iPhone with iReader App 

### ISSUE THREAD

**Issue by bikashpoudel17** [FeitianSmartcardReader/R301#4]
I brought two Feitian iR301 Smart Card reader. They have USB-C connector. I am trying to connect these reader on iPhones via USB-C to Lightning Dongle. But, the power led on the reader does not light up. But, if I connect the reader to my Mac I was able to connect and perform basic tests.

**Comment by FeitianSmartcardReader** [comment]
Hello Sir

If you can connect to iReader, show us the firmware version, we have few models, and iR301 which certified MFi, using iAP2 protocol, if your iPhone or iPad with Type-C, insert iR301, should work directly.

To have clarify Feitian product, I list here:
iR301: firmware named 8.xx
oR301: 2.xx

iR301: which using iAP2 protocol, in low level calling, we are using ExternalAccessory Protocol.
oR301: after iOS 16, Apple support CCID protocol, so oR301 which implemented based on CCID, you can call cryptokit API to communicate with reader.

Both you can call Feitian API or you can packaged your own library based on CCID or EA framework. We also open the source code of library, so you can have a better review and check how it works.
Any questions, contact us anytime, thanks

**Comment by FeitianSmartcardReader** [comment]
BTW, if your reader is lightning port, which only can support lightning Phone or iPad.

And if you  are using latest iPhone and iPad, then suggest switch to iR301 C60, which is Type-C port.

Thanks.

**Comment by bikashpoudel17** [comment]
Thanks a lot for such a prompt response. I have FEITIAN iR301 USB-C Contact-Based Smart Card Reader | C60.
This is what I get when I run pcsctest on my MAC.
```
Reader 02: Feitian iR301
Enter the reader number          : 02
Waiting for card insertion         
                                 : Command successful.
Testing SCardConnect             : Command successful.
Testing SCardStatus              : Command successful.
Current Reader Name              : Feitian iR301
Current Reader State             : 0x54
Current Reader Protocol          : 0x1
Current Reader ATR Size          : 18 (0x12)
Current Reader ATR Value         : 3B F8 13 00 00 81 31 FE 45 4A 43 4F 50 76 32 34 31 B7 
Testing SCardDisconnect          : Command successful.
Testing SCardReleaseContext      : Command successful.
Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange 
Please insert a working reader   : Command successful.
Testing SCardListReaders         : Command successful.
Reader 01: SafeNet eToken 5100
Reader 02: Feitian iR301
Enter the reader number          : 02
Waiting for card insertion         
                                 : Command successful.
Testing SCardConnect             : Command successful.
Testing SCardStatus              : Command successful.
Current Reader Name              : Feitian iR301
Current Reader State             : 0x54
Current Reader Protocol          : 0x1
Current Reader ATR Size          : 18 (0x12)
Current Reader ATR Value         : 3B F8 13 00 00 81 31 FE 45 4A 43 4F 50 76 32 34 31 B7 
Testing SCardDisconnect          : Command successful.
Testing SCardReleaseContext      : Command successful.

PC/SC Test Completed Successfully !
```
When I connect this smart card reader to my iPhone using USB-C to Lightning Dongle, then smart card reader does not get power. Do I need to have an iPhone with USB-C port?

**Comment by FeitianSmartcardReader** [comment]
Hello Bikash Poudel 

You need to have iPhone with Type-C.

The USB-CC to lightning adapter won’t work, thanks

**Comment by bpoudel7** [comment]
This issue is resolved. Thank you.
